### ISSUE TITLE
Carousel + Pagination + 2 rows

### ISSUE THREAD

**Issue by nathanjessen** [curatorio/widgets#2]
Looking to implement a custom solution that uses a carousel with pagination but also has a configurable option to choose between 1 or 2 rows on each section of the carousel. Do any of these features currently exist in the Carousel widget?

Would it be desirable to have the additional options? Or is it already possible with a combination of preexisting options?

```
var widget = new Curator.Carousel({
    carousel:{
       autoPlay:true,    // carousel will auto rotate
       autoLoad:true,     // carusel will auto load new when it reaches the end of the current page of posts
       pagination:true, // has pagination dots
       rows:2
    }
});
```

**Comment by nathanjessen** [comment]
Nevermind. Implemented with custom solution using results returned from the API. Pagination would be a nice feature though.

**Comment by sandboxdigital** [comment]
Hey Nathan, sorry for the late followup! I'd love to see how you implemented the pagination and if you don't mind I'd like to integrate it into the code base for other users. If the code has diverged from the GIT repo you can just upload a zip or something and I can integrate. And thanks for all your help on the Docs!

**Comment by nathanjessen** [comment]
It's a custom implementation that uses Angular. It would have been nice to extend the functionality of Curator's carousel but timelines prevented us from taking that route. I can't share the code yet since it is for a client and it isn't in production but essentially:
1. Get posts from api
2. Determine which slides are visible (defaults to the first 8 since we have 2 rows of 4 posts)
3. Pagination is determined by `var totalGroups = Math.ceil(scope.postsPerRequest / scope.postsPerSlide);`
4. A `scope.activeGroup` variable keeps track of which slide is being viewed and is updated any time the user hits next/previous slide button.

There are some issues that I have to figure out eventually. But this all worked for our initial implementation to demo to the client.

Thank you for putting the docs out on GitHub for us. I'll probably be putting some time on the Help section tomorrow. Let me know if you have any preference on how it is set up. I'd like to get some of the basic user flows into writing using a setup similar to the other doc sections. I haven't used Daux before but it looks straightforward enough.
